### ISSUE TITLE
Can no longer detect PS4 - no matching PS4 device found

### ISSUE THREAD

**Issue by AdamZA1** [bbriatte/homebridge-ps4-waker-platform#11]
Hello,

I have successfully had ps4-waker-platform working for several days with no issues. However, today for some reason, the platform cannot detect the PS4.

Here is the error I receive, running on MacOS in terminal.

```
[16/01/2020, 14:36:32] [PS4Waker:] Error: Could not detect any matching PS4 device
    at Detector.onTimeout (/usr/local/lib/node_modules/homebridge-ps4-waker-platform/node_modules/ps4-waker/dist/detector.js:120:16)
    at Detector.emit (events.js:317:22)
    at Detector.close (/usr/local/lib/node_modules/homebridge-ps4-waker-platform/node_modules/ps4-waker/dist/detector.js:93:8)
    at listOnTimeout (internal/timers.js:537:17)
    at processTimers (internal/timers.js:481:7)
```

Any suggestions would be very welcome.

**Comment by Tiempie** [comment]
I solved it by increasing the timout

**Comment by LordZork** [comment]
@AdamZA1 and @Tiempie 

Can either of you, or anyone else, tell me what you did to get this plugin to work in the first place?...

I installed the plugin, used one of the example configs (mine is below), and my Home app sees that my PS4 is on, and it also sees that one of my games is on.  But, the actually on/off buttons are not working... nothing happens.  They just time out I guess.  Also, nothing happens in the Homebridge log when I click the on/off button within the Home app, for the PS4 or the game.

`        {
            "platform": "PS4WakerPlatform",
            "name": "PS4Waker",
            "accessories": [
                {
                    "serial": "MFXXXXXXXXX",
                    "model": "CUH-XXXXB",
                    "name": "PS4",
                    "apps": [
                        {
                            "id": "CUSA08829",
                            "name": "Modern Warfare"
                        },
                        {
                            "id": "CUSA07022",
                            "name": "Fortnite"
                        }
                    ]
                }
            ]
        }
`

Is there something else I'm supposed to do with the config?  Or, am I supposed to also install the [PS4 Waker](https://github.com/dhleong/ps4-waker) plugin?

Everything is in the Home app and I didn't get any errors from the Homebridge logs, and the status of the console and loaded game shows, but the buttons are just not doing anything, and nothing is happening in the log when I push those buttons.  

Any help would be greatly appreciated, thanks!!

**Comment by LordZork** [comment]
@AdamZA1 and @Tiempie 

Can either of you, or anyone else, tell me what you did to get this plugin to work in the first place?...

I installed the plugin, used one of the example configs (mine is below), and my Home app sees that my PS4 is on, and it also sees that one of my games is on.  But, the actually on/off buttons are not working... nothing happens.  They just time out I guess.  Also, nothing happens in the Homebridge log when I click the on/off button within the Home app, for the PS4 or the game.


        {
            "platform": "PS4WakerPlatform",
            "name": "PS4Waker",
            "accessories": [
                {
                    "serial": "MFXXXXXXXXX",
                    "model": "CUH-XXXXB",
                    "name": "PS4",
                    "apps": [
                        {
                            "id": "CUSA08829",
                            "name": "Modern Warfare"
                        },
                        {
                            "id": "CUSA07022",
                            "name": "Fortnite"
                        }
                    ]
                }
            ]
        }

Is there something else I'm supposed to do with the config?  Or, am I supposed to also install the [PS4 Waker](https://github.com/dhleong/ps4-waker) plugin?

Everything is in the Home app and I didn't get any errors from the Homebridge logs, and the status of the console and loaded game shows, but the buttons are just not doing anything, and nothing is happening in the log when I push those buttons.  

Any help would be greatly appreciated, thanks!!

**Comment by LordZork** [comment]
Also, am I supposed to somehow pair the plugin with my PS4?  I have it paired with the Second Screen app... is that enough, or no?

**Comment by AdamZA1** [comment]
I have both the PS4 Waker plugin as well as the PS4 Waker Platform installed - couldn't comment on one without the other - I always troubleshoot using PS4 Waker itself. As such, I can only advise you if you want to install that too. I too found there wasn't much guidance on the Homebridge plugin.

You do need to bind PS4 Waker to the PS4 - the second screen app is only relevant in the setup to get the credentials for PS4 Waker to pretend to be another PS4 in order to control yours.

If you install PS4 Waker itself and then follow the setup (or run ps4-waker search) then when prompted, go to add new device on your PS4 and enter the code into the terminal window. After that it'll show up in the list of devices on your PS4. Make sure you have enabled wake on LAN in the PS4 network settings.

**Comment by LordZork** [comment]
@AdamZA1 

I have PS4-Waker installed now.  I am not sure what setup there is to follow?  Where do I find this setup?  Also, I ran ps4 waker search, but I am not sure what to do as far as putting the code in terminal?

**Comment by AdamZA1** [comment]
Once PS4 Walker detects the PS4, it should ask you to begin the pairing process.

**Comment by LordZork** [comment]
@AdamZA1 I've got it working now!  I greatly appreciate your help and the info you've provided!

Thank you!!

**Comment by AdamZA1** [comment]
You’re welcome. Enjoy.

**Comment by corpsell** [comment]
> I solved it by increasing the timout

How does one do this?

The README states default is 10s which yields a 50/50 shot of it executing properly.

I’ve input `ps4-waker -t 20000` To try and double the default, but when I run this command, there is no feedback aside from the PS4 turning on. Where is the files can I manually check/change this default 10s value?

**Comment by pukserk** [comment]
> Hello,
> 
> I have successfully had ps4-waker-platform working for several days with no issues. However, today for some reason, the platform cannot detect the PS4.
> 
> Here is the error I receive, running on MacOS in terminal.
> 
> ```
> [16/01/2020, 14:36:32] [PS4Waker:] Error: Could not detect any matching PS4 device
>     at Detector.onTimeout (/usr/local/lib/node_modules/homebridge-ps4-waker-platform/node_modules/ps4-waker/dist/detector.js:120:16)
>     at Detector.emit (events.js:317:22)
>     at Detector.close (/usr/local/lib/node_modules/homebridge-ps4-waker-platform/node_modules/ps4-waker/dist/detector.js:93:8)
>     at listOnTimeout (internal/timers.js:537:17)
>     at processTimers (internal/timers.js:481:7)
> ```
> 
> Any suggestions would be very welcome.

I have the same problem. Did you try to fix it?

**Comment by AdamZA1** [comment]
Try turning off your PS4 fully instead of just putting it to sleep and also try restarting the network adapter on the computer running homebridge or ps4waker, or restart the computer itself. These two actions usually re-establish the connection for me.
