### ISSUE TITLE
Login connect refused; retrying soon

### ISSUE THREAD

**Issue by duguzuyang** [bbriatte/homebridge-ps4-waker-platform#4]
I'm running Homebridge on [Docker](https://hub.docker.com/r/oznu/homebridge/), with the config file like:
```
{
	"platform": "PS4WakerPlatform",
	"name": "PS4Waker",
	"accessories": [{
		"serial": "MF817609670",
		"model": "CUH-7215B",
		"name": "Homebridge",
		"credentials": "/homebridge/.ps4-wake.credentials.json"
	}]
}
```

And I get
```
[PS4Waker] Searching accessories...
[PS4Waker] Found device [Zuyang-PS4-Pro]
[PS4Waker] Finish searching accessories

```

But when I try to wake up the PS4 using homebridge, I get
```
Login connect refused; retrying soon
Login connect refused; retrying soon
Login connect refused; retrying soon
Login connect refused; retrying soon
Error logging in: { Error: connect ECONNREFUSED 192.168.1.215:997
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.215',
  port: 997 }
[8/9/2019, 4:43:13 AM] [PS4Waker] Error: No socket
    at _this11._waker.wake (/homebridge/node_modules/homebridge-ps4-waker-platform/node_modules/ps4-waker/dist/device.js:561:38)
    at Ps4Socket.socket.once.on.e (/homebridge/node_modules/homebridge-ps4-waker-platform/node_modules/ps4-waker/dist/waker.js:374:5)
    at Ps4Socket.emit (events.js:198:13)
    at Socket.client.on.err (/homebridge/node_modules/homebridge-ps4-waker-platform/node_modules/ps4-waker/dist/ps4socket.js:164:10)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Jafalex** [comment]
Hi there, I have the same issue, did you find a fix?

**Comment by codyc1515** [comment]
Can you ping 192.168.1.215 from your Homebridge device?

**Comment by rcuijpers** [comment]
So, I had the same error whilst trying to power on the PS4 Pro in my house. Looked around for all kinds of sollutions but it turns out i had some stuff turned off in the PS4's power saving settings... Argh! This should be something explained in the readme.  Sollution for me: **To enable the "available in rest mode" function on the PS4™ console
Make sure that the PS4™ console has been paired with the Mobile (or this plugin) device using the PS4 Remote Play app.
PS4™: Select Settings > Power Save Settings > Set Function Available in Rest Mode > Enable turing On PS4 from Network.**

**Comment by temkalol41** [comment]
Thank you, man! It's work!
